set(GEOMETRY_SOURCES
  src/Primitives/point.cpp
  src/Primitives/vector.cpp
  src/Primitives/line.cpp
  src/Primitives/ray.cpp
  src/Primitives/plane.cpp
  src/utils/numerical_utils.cpp
  src/Queries/intersect.cpp
  src/Queries/parallel.cpp
)