set(GEOMETRY_TEST_SOURCES
  tests/Primitives/test_point.cpp
  tests/Primitives/test_vector.cpp
  tests/Primitives/test_line.cpp
  tests/Primitives/test_ray.cpp
  tests/Primitives/test_plane.cpp
  tests/Queries/test_intersect.cpp
  tests/Queries/test_parallel.cpp
  tests/Queries/test_project.cpp
  tests/Queries/test_distance.cpp
)